#cloud-config
# vim: syntax=yaml
#

write_files:
-   encoding: b64
    content: W21vbmdvZGItb3JnLTMuMl0NCm5hbWU9TW9uZ29EQiBSZXBvc2l0b3J5DQpiYXNldXJsPWh0dHBzOi8vcmVwby5tb25nb2RiLm9yZy95dW0vcmVkaGF0LyRyZWxlYXNldmVyL21vbmdvZGItb3JnLzMuMi94ODZfNjQvDQpncGdjaGVjaz0wDQplbmFibGVkPTE=
    owner: root:root
    path: /etc/yum.repos.d/mongodb-org-3.2.repo
    permissions: '0664'

runcmd:
  - [ sh, -xc, "cd /home/opc/meanjs && gulp" ]
  - [ sh, -xc, "touch /tmp/signal"]
